### ISSUE TITLE
Feature request: Bloom

### ISSUE THREAD

**Issue by Schwarzbaer** [rayanalysis/panda3d-complexpbr#1]
I request bloom effect.

**Comment by rayanalysis** [comment]
Thanks for the feature request. I will look into how I can adapt something like the CommonFilters bloom (which is supported, at the expense of screenspace_init() currently) to the native postprocessing.

**Comment by rayanalysis** [comment]
Bloom has now been implemented. See these sample screenshots and feature Usage notes below. The bloom_intensity defaults to 0.0 (off).

![complexpbr_bloom_screen_1](https://user-images.githubusercontent.com/3117958/236597111-a3ee81e8-2072-434e-97a2-1bf561b5189a.png)

![complexpbr_bloom_screen_2](https://user-images.githubusercontent.com/3117958/236597145-9e498092-18fa-4b7b-b78a-edb157c2e36b.png)

# example of how to set up bloom -- complexpbr.screenspace_init() must have been called first
screen_quad = base.screen_quad

bloom_intensity = 5.0  # bloom defaults to 0.0 / off
bloom_blur_width = 10
bloom_samples = 6
bloom_threshold = 0.7

screen_quad.set_shader_input("bloom_intensity", bloom_intensity)
screen_quad.set_shader_input("bloom_threshold", bloom_threshold)
screen_quad.set_shader_input("bloom_blur_width", bloom_blur_width)
screen_quad.set_shader_input("bloom_samples", bloom_samples)
