### ISSUE TITLE
Exported landscape model has wrong colors

### ISSUE THREAD

**Issue by kergalym** [rayanalysis/panda3d-complexpbr#3]
Hi,
I exported landscape from blender as glTF but it renders as redish:
![Screenshot_20230929_002754](https://github.com/rayanalysis/panda3d-complexpbr/assets/9489149/28b71c43-5289-453d-9fbd-81733f1f8e78)

Here is material setup:
![image](https://github.com/rayanalysis/panda3d-complexpbr/assets/9489149/55713c85-4d5e-4138-bce2-13d29ee1dbc6)

What I tried:
* I replaced material with default one
* imported model into fresh Blender project then exported as glTF
* re-exported arena scene (which is part of Panda3D-Arena-FPS-Sample-Program), but it renders fine
* changed lights position to make them stay higher

I use:
Blender 3.0.1
Panda3D 1.11

**Comment by kergalym** [comment]
![Screenshot_20230929_020056](https://github.com/rayanalysis/panda3d-complexpbr/assets/9489149/75b8eb25-36b8-4b62-8da8-689c41c0cca9)
Arena geometry with landscape texture, rendered fine

![Screenshot_20230929_021214](https://github.com/rayanalysis/panda3d-complexpbr/assets/9489149/f1803217-3827-4454-b586-20741c17048b)
![Screenshot_20230929_021425](https://github.com/rayanalysis/panda3d-complexpbr/assets/9489149/1cd500b9-5848-400e-a606-c1fbea5d1522)

Plain with  landscape texture, rendered black (this is geometry scale, it must be unified)

**Comment by kergalym** [comment]
So texture could be any, there is only geometry rendering problem

**Comment by rayanalysis** [comment]
Here's a landscape I slapped together in about an hour. All I did differently from the Arena FPS Sample Program was boost the directional light intensity a bit:

Blender:

![blender_screen_2](https://cdn.discordapp.com/attachments/533048345791299634/1157109295037558804/image.png?ex=65176981&is=65161801&hm=0b9e5d6d9db57d89902816948b029b4805ccfca7691c6a55f6f5992b48f84c0b&)

complexpbr:

![complexpbr_screen_1](https://cdn.discordapp.com/attachments/533048345791299634/1157107214943797308/image.png?ex=65176792&is=65161612&hm=bda652e1df6e949eea5791c9864cb5f9aaaee2970bdd314a3bf0f550628904ba&)

![complexpbr_screen_2](https://cdn.discordapp.com/attachments/533048345791299634/1157108048469446879/image.png?ex=65176858&is=651616d8&hm=906713c58ef1ebce6a7303fd7a2e5bd6b1ca000b3efed43a2ce3ff3bda15a502&)

**Comment by kergalym** [comment]
Exported landscape made with A.N.T Landscape addon
![Screenshot_20230929_144113](https://github.com/rayanalysis/panda3d-complexpbr/assets/9489149/4c94c14e-8273-4fb7-aadb-ed4a6e67ea3d)

Renders fine

Here is [link](https://drive.google.com/file/d/19CF17SiK_7TEtxsdvX-peCggd6uF4s4S/view?usp=sharing) to broken landscape which stays red, you might be interested in

**Comment by rayanalysis** [comment]
Looks like this was down to a specific model, as we have both demonstrated correct-looking landscapes here. Closing.
