### ISSUE TITLE
TypeError: NodePath.set_shader() argument 1 must be Shader, not NoneType

### ISSUE THREAD

**Issue by MonsieurBerthier** [rayanalysis/panda3d-complexpbr#5]
I have the following error traceback when trying to use complexpbr:

```
"C:\Program Files\Panda3D-1.10.13-x64\python\python.exe" D:\Workspace\Python\project-naer\main.py 
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
AL lib: (EE) ALCwasapiPlayback_resetProxy: Audio client returned buffer_len < period*2; expect break up
:shader(error): Could not find shader file: D:\Workspace\Python\project-naer\library\complexpbr\ibl_v.vert
:express(warning): Filename uses Windows-style path: D:\Workspace\Python\project-naer\library\complexpbr\output_brdf_lut.png
:express(warning):   expected Unix-style path: /d/Workspace/Python/project-naer/library/complexpbr/output_brdf_lut.png
:gobj(error): Texture::read() - couldn't read: D:\Workspace\Python\project-naer\library\complexpbr\output_brdf_lut.png
:express(warning): Filename uses Windows-style path: D:\Workspace\Python\project-naer\library\complexpbr\output_brdf_lut.png
:express(warning):   expected Unix-style path: /d/Workspace/Python/project-naer/library/complexpbr/output_brdf_lut.png
:gobj(error): Unable to find texture "D:\Workspace\Python\project-naer\library\complexpbr\output_brdf_lut.png" on model-path /d/Workspace/Python/project-naer;/c/Program Files/Panda3D-1.10.13
-x64/etc/..;/c/Program Files/Panda3D-1.10.13-x64/etc/../models
complexpbr message: Defaulting to dummy LUT.
Traceback (most recent call last):
  File "D:\Workspace\Python\project-naer\main.py", line 213, in <module>
    main = Main()
  File "D:\Workspace\Python\project-naer\main.py", line 56, in __init__
    library.complexpbr.apply_shader(self.render)
  File "D:\Workspace\Python\project-naer\library\complexpbr\__init__.py", line 165, in apply_shader
    complexpbr_rig_init(node, intensity=intensity, lut_fill=lut_fill)
  File "D:\Workspace\Python\project-naer\library\complexpbr\__init__.py", line 128, in complexpbr_rig_init
    node.set_shader(base.complexpbr_shader)
TypeError: NodePath.set_shader() argument 1 must be Shader, not NoneType

Process finished with exit code 1
```

Here is my code (simplified):
```
class Main(direct.showbase.ShowBase.ShowBase):

    def __init__(self) -> None:

        super().__init__(self)
        library.complexpbr.apply_shader(self.render)
```

**Comment by rayanalysis** [comment]
Hi there, thank you for submitting this error report. It looks like you are importing complexpbr from a different module you've called "library". I actually haven't tested complexpbr for this use case, so I may need to do so and then iterate before this will work as expected. You can reference https://github.com/rayanalysis/Panda3D-Arena-FPS-Sample-Program to see the "standard" way of importing and using complexpbr.

**Comment by MonsieurBerthier** [comment]
Thanks for your reply!
I also tried to import it from the same folder as my `main.py` file and the result is the same.

**Comment by rayanalysis** [comment]
If I may, what happens when you run the Arena FPS sample program?

**Comment by MonsieurBerthier** [comment]
Interesting! I have the same error.
I tried with `complexpbr` located in Python's `site-packages` folder.

**Comment by rayanalysis** [comment]
Here is a .zip of the current complexpbr wheel. Uninstall any complexpbr versions you may have, and then use "pip install" with this .whl file once you unzip it.

You may have copied the complexpbr folder itself into your site-packages, which would make this the second time it's happened (sigh), and is not a supported way of installing complexpbr. I will get this on pypi (pip) sometime but I've been too busy this year so far.

[panda3d_complexpbr-0.5.3-py3-none-any.zip](https://github.com/rayanalysis/panda3d-complexpbr/files/13047347/panda3d_complexpbr-0.5.3-py3-none-any.zip)

**Comment by rayanalysis** [comment]
Nevermind, I see the issue now. It was probably created when I accepted the last PR. I will correct and update the repo.

**Comment by MonsieurBerthier** [comment]
Excellent news! I'll wait for the update!

**Comment by rayanalysis** [comment]
Thanks, I have just checked in that reversion commit. I've attached a new .whl below or you can build yourself from the latest commit.

Let me know how it goes, I know there is a bug on Python 3.8 so please test it with a recent Python version, IE 3.11.4
 
[panda3d_complexpbr-0.5.3-py3-none-any.zip](https://github.com/rayanalysis/panda3d-complexpbr/files/13047724/panda3d_complexpbr-0.5.3-py3-none-any.zip)

**Comment by MonsieurBerthier** [comment]
Thanks for the update! It's better: now it runs!
Now, I just need to figure out why my scene is very dark, almost like there are no lights (I can still see objects).
At the moment, I am using the default 3.7 provided in P3D's SDK, which type of bug are you referring to?

**Comment by rayanalysis** [comment]
I haven't taken the time to fully diagnose the issue on Python <=3.8 but it involves node transformation issues. I highly recommend using Python 3.11 or higher.

Closing as the problem has been solved. Feel free to open another issue if any come up and are not related to Python version support.

**Comment by ekiefl** [comment]
I experience the same error in my project. Here is the PR with the changes I made: https://github.com/ekiefl/pooltool/pull/144

Traceback:

```
Known pipe types:
  CocoaGraphicsPipe
(all display modules loaded.)
:shader(error): Could not find shader file: ibl_v.vert
Traceback (most recent call last):
  File "/Users/evan/anaconda3/envs/pooltool-dev/bin/run-pooltool", line 6, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/evan/anaconda3/envs/pooltool-dev/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evan/anaconda3/envs/pooltool-dev/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/evan/anaconda3/envs/pooltool-dev/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evan/anaconda3/envs/pooltool-dev/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evan/Software/pooltool_ml/pooltool/pooltool/main.py", line 14, in run
    play = Game(config)
           ^^^^^^^^^^^^
  File "/Users/evan/Software/pooltool_ml/pooltool/pooltool/ani/animate.py", line 460, in __init__
    Interface.__init__(self, config=config)
  File "/Users/evan/Software/pooltool_ml/pooltool/pooltool/ani/animate.py", line 137, in __init__
    complexpbr.apply_shader(self.render)
  File "/Users/evan/anaconda3/envs/pooltool-dev/lib/python3.12/site-packages/complexpbr/__init__.py", line 198, in apply_shader
    complexpbr_rig_init(node, intensity=intensity, lut_fill=lut_fill)
  File "/Users/evan/anaconda3/envs/pooltool-dev/lib/python3.12/site-packages/complexpbr/__init__.py", line 150, in complexpbr_rig_init
    node.set_shader(base.complexpbr_shader)
TypeError: NodePath.set_shader() argument 1 must be Shader, not NoneType
```

I tested out complexpbr with `arena.py` and no error is observed (though I'm getting whiteout graphics, probably due to me using an 8 year old mac).

<img width="1278" alt="image" src="https://github.com/user-attachments/assets/48e468d1-04a8-4216-a246-3660589bb766">
