### ISSUE TITLE
Composition for vertex shader?

### ISSUE THREAD

**Issue by Augustifolia** [rayanalysis/panda3d-complexpbr#8]
I just tested out your addition of composition to be able to customize the complexpbr shaders and it seems like a useful feature. However it would be nice if it were possible to do the same for the vertex shader as well. For example for creating animated grass or a moving water surface.  

I also noticed that every time I run my program complexpbr creates a new shader file in the projects main directory. That does quickly end up cluttering the main directory. It would be nice if I could specify a sub-directory in my project where complexpbr should store the shader files. Or perhaps that I could specify a name for the custom shaders instead of complexpbr generating a name. That way the old file could be overwriten instead of a new file being created every time.

What are your thoughts about this? I can put together a PR if you are interested.

**Comment by rayanalysis** [comment]
Thanks for the suggestions. Yes, I was expecting this to come up sooner than later -- the generation of unique shader file numbers each append_shader() call was a quick solution to avoid the case where a user might call append_shader() at multiple different points in their program structure. My main concern there was some point in the program using the wrong custom shader file.

There may be permission issues generically creating a new directory, but assuming the directory already exists in a user's program structure, specifying that folder's name shouldn't be an issue. If you'd like to work on this PR, I'd certainly be happy to review it.

**Comment by rayanalysis** [comment]
With regard to modifying the model-level vertex shader file, I'd prefer that to take place after the existing three inputs to append_shader() . So we could do something like `complexpbr.append_shader(node=None,body_mod='',main_mod='',vert_body_mod='',vert_main_mod='',...)`, if that's what you were thinking.

The next thing that I imagine will come up is modifying the screenspace shaders. I'd prefer to leave those alone for now.

**Comment by developer-1v** [comment]
Great ideas.

**Comment by rayanalysis** [comment]
I went ahead and implemented most of this in the composition branch today. You can check out my current changes at https://github.com/rayanalysis/panda3d-complexpbr/tree/composition

So as of now, in the composition branch, one may add their vertex body mod and vertex main mods to the arguments following the initial fragment modification inputs like so:

```
        # call the append_shader() function
        custom_body_mod = 'float default_noise(vec2 n)\n{\nfloat n2  = fract(sin(dot(n.xy,vec2(11.78,77.443)))*44372.7263);\nreturn n2;\n}'
        custom_main_mod = 'o_color += default_noise(vec2(2.3,3.3));'
        custom_vert_body_mod = 'float default_noise(vec2 n)\n{\nreturn n[0];\n}'
        custom_vert_main_mod = 'float whatever = default_noise(vec2(2.3,3.3));'
        complexpbr.append_shader(test_sphere, custom_body_mod, custom_main_mod, custom_vert_body_mod, custom_vert_main_mod)
```
...and to sweeten the deal, I've expanded the existing shader cleanup functionality to look for and delete any shader files generated by append_shader() like so:

`
complexpbr.remove_shader_files()`

...which will totally clean up any number of complexpbr-generated shader files. Keep in mind that using this cleanup option in a distributable build will fail on the user end, as complexpbr will be unable to locate files on consecutive runs. The arbitrary proliferation of append_shader() generated custom shader files will remain an open issue for now in distributable builds, but we can open something separately for that and the whole directory creation issue.

Closing this "Composition for vertex shader" specific issue.

**Comment by Augustifolia** [comment]
That sounds good to me. Thank you for fixing this!
